import {useEffect, useRef, useState} from "react";

const NetworkImage = ({tabContainer, activeNetwork}) => {
    const [loading, setLoading] = useState(false)
    useEffect(() => {
        scrollToImage()
    }, [loading])

    const imgRef = useRef(null)

    const handleImageLoaded = () => {
        setLoading(true)
    }
    const scrollToImage = () => {
        // window.scroll({top: tabContainer.scrollHeight, behavior: "smooth"})
        tabContainer.scrollIntoView({block: "start", behavior: 'smooth'})
    }

    return (
        <div className={'tabContent'}>

            <div className={'result-container'}>
                <img alt={`image generated by ${activeNetwork.name}`} onLoad={handleImageLoaded} ref={imgRef}
                     src={activeNetwork.image}/>
            </div>
        </div>
    )
}
export default NetworkImage