import {useEffect, useRef, useState} from "react";
import './NetworkImage.scss'

const NetworkImage = ({activeNetwork, scrollToImage, tabContainer}) => {
    const [loading, setLoading] = useState(false)
    useEffect(() => {
        // scrollToImage()
        scrollToImage()
    }, [loading])

    const handleImageLoaded = () => {
        setLoading(true)
    }

    const containerHeight = document.documentElement.clientHeight - 210


    return (
        <div style={{
            height: loading ? 'auto' : containerHeight + 'px'
        }} className={'result-container'}>
            <img alt={`image generated by ${activeNetwork.name}`} onLoad={handleImageLoaded}
                 src={activeNetwork.image}/>
        </div>
    )
}
export default NetworkImage